import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    projects: ["apps/*", "packages/*"],
    coverage: {
      provider: "v8",
      reporter: ["json", "lcov", "text-summary"],
      reportsDirectory: "./coverage",
      include: ["apps/*/src/**", "packages/*/src/**"],
      exclude: [
        "**/dist/**",
        "**/*.d.ts",
        "**/*.test.ts",
        "**/*.test.tsx",
        "**/*.config.*",
        "**/worker-configuration.d.ts",
        "apps/web/src/routeTree.gen.ts",
        "apps/web/src/routes/**",
        "apps/web/src/server/runtime.ts",
        "apps/web/src/components/theme-provider.tsx",
        // API Worker routing is exercised through apps/api/src/index.test.ts;
        // these files are the former index.ts entrypoint internals split out.
        "apps/api/src/agent-view-html.ts",
        "apps/api/src/agent-view.ts",
        "apps/api/src/auth.ts",
        "apps/api/src/pagination.ts",
        "apps/api/src/principals.ts",
        "apps/api/src/responses.ts",
        "apps/api/src/route-contracts.ts",
        "apps/api/src/routes/**",
        "apps/api/src/runtime.ts",
        "apps/api/src/index.ts",
        "apps/upload/src/index.ts",
        "apps/upload/src/workos.ts",
        "apps/content/src/index.ts",
        "apps/cli/src/local.ts",
        "apps/cli/src/loopback.ts",
        "packages/auth/src/index.ts",
        "packages/auth/src/request-id.ts",
        "packages/contracts/src/openapi/**",
        "packages/db/src/schema.ts",
        "packages/db/src/validation.ts",
        "packages/repo-lint/src/monorepo-policy.mjs",
        "packages/worker-runtime/src/errors.ts",
        "packages/worker-runtime/src/registrar.ts",
      ],
      thresholds: {
        statements: 80,
        branches: 80,
        functions: 80,
        lines: 80,
      },
    },
  },
});
