import { DEFAULT_UPLOAD_SESSION_TTL_MS, MAX_ARTIFACT_BYTES, SECONDS_PER_DAY, USAGE_POLICY } from "@agent-paste/config";

export { DEFAULT_UPLOAD_SESSION_TTL_MS, MAX_ARTIFACT_BYTES, SECONDS_PER_DAY, USAGE_POLICY };

export const DEFAULT_AUTO_DELETION_DAYS = Math.floor(USAGE_POLICY.default_ttl_seconds / SECONDS_PER_DAY);
export const MIN_AUTO_DELETION_DAYS = Math.floor(USAGE_POLICY.min_ttl_seconds / SECONDS_PER_DAY);
export const MAX_AUTO_DELETION_DAYS = Math.floor(USAGE_POLICY.max_ttl_seconds / SECONDS_PER_DAY);
