/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HealthzRouteImport } from './routes/healthz'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlPublicIdRouteImport } from './routes/al.$publicId'
import { Route as AuthedSettingsRouteImport } from './routes/_authed.settings'
import { Route as AuthedKeysRouteImport } from './routes/_authed.keys'
import { Route as AuthedDashboardRouteImport } from './routes/_authed.dashboard'
import { Route as AuthedAuditRouteImport } from './routes/_authed.audit'
import { Route as AuthedAdminRouteImport } from './routes/_authed.admin'
import { Route as AuthedAccessLinksRouteImport } from './routes/_authed.access-links'
import { Route as AuthedArtifactsIndexRouteImport } from './routes/_authed.artifacts.index'
import { Route as ApiAuthSignOutRouteImport } from './routes/api/auth/sign-out'
import { Route as ApiAuthSignInRouteImport } from './routes/api/auth/sign-in'
import { Route as ApiAuthCallbackRouteImport } from './routes/api/auth/callback'
import { Route as AuthedArtifactsArtifactIdRouteImport } from './routes/_authed.artifacts.$artifactId'

const HealthzRoute = HealthzRouteImport.update({
  id: '/healthz',
  path: '/healthz',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlPublicIdRoute = AlPublicIdRouteImport.update({
  id: '/al/$publicId',
  path: '/al/$publicId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedKeysRoute = AuthedKeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAuditRoute = AuthedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminRoute = AuthedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAccessLinksRoute = AuthedAccessLinksRouteImport.update({
  id: '/access-links',
  path: '/access-links',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedArtifactsIndexRoute = AuthedArtifactsIndexRouteImport.update({
  id: '/artifacts/',
  path: '/artifacts/',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiAuthSignOutRoute = ApiAuthSignOutRouteImport.update({
  id: '/api/auth/sign-out',
  path: '/api/auth/sign-out',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSignInRoute = ApiAuthSignInRouteImport.update({
  id: '/api/auth/sign-in',
  path: '/api/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthCallbackRoute = ApiAuthCallbackRouteImport.update({
  id: '/api/auth/callback',
  path: '/api/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedArtifactsArtifactIdRoute =
  AuthedArtifactsArtifactIdRouteImport.update({
    id: '/artifacts/$artifactId',
    path: '/artifacts/$artifactId',
    getParentRoute: () => AuthedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/healthz': typeof HealthzRoute
  '/access-links': typeof AuthedAccessLinksRoute
  '/admin': typeof AuthedAdminRoute
  '/audit': typeof AuthedAuditRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/keys': typeof AuthedKeysRoute
  '/settings': typeof AuthedSettingsRoute
  '/al/$publicId': typeof AlPublicIdRoute
  '/artifacts/$artifactId': typeof AuthedArtifactsArtifactIdRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/sign-in': typeof ApiAuthSignInRoute
  '/api/auth/sign-out': typeof ApiAuthSignOutRoute
  '/artifacts/': typeof AuthedArtifactsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/healthz': typeof HealthzRoute
  '/access-links': typeof AuthedAccessLinksRoute
  '/admin': typeof AuthedAdminRoute
  '/audit': typeof AuthedAuditRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/keys': typeof AuthedKeysRoute
  '/settings': typeof AuthedSettingsRoute
  '/al/$publicId': typeof AlPublicIdRoute
  '/artifacts/$artifactId': typeof AuthedArtifactsArtifactIdRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/sign-in': typeof ApiAuthSignInRoute
  '/api/auth/sign-out': typeof ApiAuthSignOutRoute
  '/artifacts': typeof AuthedArtifactsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/healthz': typeof HealthzRoute
  '/_authed/access-links': typeof AuthedAccessLinksRoute
  '/_authed/admin': typeof AuthedAdminRoute
  '/_authed/audit': typeof AuthedAuditRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/keys': typeof AuthedKeysRoute
  '/_authed/settings': typeof AuthedSettingsRoute
  '/al/$publicId': typeof AlPublicIdRoute
  '/_authed/artifacts/$artifactId': typeof AuthedArtifactsArtifactIdRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/sign-in': typeof ApiAuthSignInRoute
  '/api/auth/sign-out': typeof ApiAuthSignOutRoute
  '/_authed/artifacts/': typeof AuthedArtifactsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/healthz'
    | '/access-links'
    | '/admin'
    | '/audit'
    | '/dashboard'
    | '/keys'
    | '/settings'
    | '/al/$publicId'
    | '/artifacts/$artifactId'
    | '/api/auth/callback'
    | '/api/auth/sign-in'
    | '/api/auth/sign-out'
    | '/artifacts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/healthz'
    | '/access-links'
    | '/admin'
    | '/audit'
    | '/dashboard'
    | '/keys'
    | '/settings'
    | '/al/$publicId'
    | '/artifacts/$artifactId'
    | '/api/auth/callback'
    | '/api/auth/sign-in'
    | '/api/auth/sign-out'
    | '/artifacts'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/healthz'
    | '/_authed/access-links'
    | '/_authed/admin'
    | '/_authed/audit'
    | '/_authed/dashboard'
    | '/_authed/keys'
    | '/_authed/settings'
    | '/al/$publicId'
    | '/_authed/artifacts/$artifactId'
    | '/api/auth/callback'
    | '/api/auth/sign-in'
    | '/api/auth/sign-out'
    | '/_authed/artifacts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  HealthzRoute: typeof HealthzRoute
  AlPublicIdRoute: typeof AlPublicIdRoute
  ApiAuthCallbackRoute: typeof ApiAuthCallbackRoute
  ApiAuthSignInRoute: typeof ApiAuthSignInRoute
  ApiAuthSignOutRoute: typeof ApiAuthSignOutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/healthz': {
      id: '/healthz'
      path: '/healthz'
      fullPath: '/healthz'
      preLoaderRoute: typeof HealthzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/al/$publicId': {
      id: '/al/$publicId'
      path: '/al/$publicId'
      fullPath: '/al/$publicId'
      preLoaderRoute: typeof AlPublicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/keys': {
      id: '/_authed/keys'
      path: '/keys'
      fullPath: '/keys'
      preLoaderRoute: typeof AuthedKeysRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/audit': {
      id: '/_authed/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthedAuditRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin': {
      id: '/_authed/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthedAdminRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/access-links': {
      id: '/_authed/access-links'
      path: '/access-links'
      fullPath: '/access-links'
      preLoaderRoute: typeof AuthedAccessLinksRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/artifacts/': {
      id: '/_authed/artifacts/'
      path: '/artifacts'
      fullPath: '/artifacts/'
      preLoaderRoute: typeof AuthedArtifactsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/auth/sign-out': {
      id: '/api/auth/sign-out'
      path: '/api/auth/sign-out'
      fullPath: '/api/auth/sign-out'
      preLoaderRoute: typeof ApiAuthSignOutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/sign-in': {
      id: '/api/auth/sign-in'
      path: '/api/auth/sign-in'
      fullPath: '/api/auth/sign-in'
      preLoaderRoute: typeof ApiAuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/callback': {
      id: '/api/auth/callback'
      path: '/api/auth/callback'
      fullPath: '/api/auth/callback'
      preLoaderRoute: typeof ApiAuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/artifacts/$artifactId': {
      id: '/_authed/artifacts/$artifactId'
      path: '/artifacts/$artifactId'
      fullPath: '/artifacts/$artifactId'
      preLoaderRoute: typeof AuthedArtifactsArtifactIdRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedAccessLinksRoute: typeof AuthedAccessLinksRoute
  AuthedAdminRoute: typeof AuthedAdminRoute
  AuthedAuditRoute: typeof AuthedAuditRoute
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedKeysRoute: typeof AuthedKeysRoute
  AuthedSettingsRoute: typeof AuthedSettingsRoute
  AuthedArtifactsArtifactIdRoute: typeof AuthedArtifactsArtifactIdRoute
  AuthedArtifactsIndexRoute: typeof AuthedArtifactsIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAccessLinksRoute: AuthedAccessLinksRoute,
  AuthedAdminRoute: AuthedAdminRoute,
  AuthedAuditRoute: AuthedAuditRoute,
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedKeysRoute: AuthedKeysRoute,
  AuthedSettingsRoute: AuthedSettingsRoute,
  AuthedArtifactsArtifactIdRoute: AuthedArtifactsArtifactIdRoute,
  AuthedArtifactsIndexRoute: AuthedArtifactsIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  HealthzRoute: HealthzRoute,
  AlPublicIdRoute: AlPublicIdRoute,
  ApiAuthCallbackRoute: ApiAuthCallbackRoute,
  ApiAuthSignInRoute: ApiAuthSignInRoute,
  ApiAuthSignOutRoute: ApiAuthSignOutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
