import type { ErrorCode } from "./common.js";
import type { Scope } from "./enums.js";

export type AppSurface = "api" | "upload" | "content" | "admin";
export type HttpMethod = "GET" | "POST" | "PATCH" | "DELETE";
export type AuthRequirement = "none" | "any_authenticated" | "member_dashboard" | "operator";
export type IdempotencyRequirement = "none" | "required" | "optional";

export type RouteContract = {
  id: string;
  app: AppSurface;
  method: HttpMethod;
  path: string;
  auth: AuthRequirement;
  scopes: readonly Scope[];
  idempotency: IdempotencyRequirement;
  requestSchema?: string;
  responseSchema: string;
  errors: readonly ErrorCode[];
};

const commonReadErrors = [
  "not_authenticated",
  "insufficient_scope",
  "artifact_not_found",
  "database_unavailable",
] as const;
const commonMutationErrors = [
  "not_authenticated",
  "insufficient_scope",
  "invalid_idempotency_key",
  "idempotency_in_flight",
  "artifact_not_found",
  "database_unavailable",
] as const;

export const routeContracts = [
  {
    id: "whoami.get",
    app: "api",
    method: "GET",
    path: "/v1/whoami",
    auth: "any_authenticated",
    scopes: [],
    idempotency: "none",
    responseSchema: "WhoamiResponse",
    errors: ["not_authenticated", "database_unavailable"],
  },
  {
    id: "usagePolicy.get",
    app: "api",
    method: "GET",
    path: "/v1/usage-policy",
    auth: "any_authenticated",
    scopes: [],
    idempotency: "none",
    responseSchema: "UsagePolicy",
    errors: ["not_authenticated", "database_unavailable"],
  },
  {
    id: "artifacts.list",
    app: "api",
    method: "GET",
    path: "/v1/artifacts",
    auth: "any_authenticated",
    scopes: ["read"],
    idempotency: "none",
    requestSchema: "PaginationRequest",
    responseSchema: "ArtifactListResponse",
    errors: commonReadErrors,
  },
  {
    id: "artifacts.get",
    app: "api",
    method: "GET",
    path: "/v1/artifacts/{artifact_id}",
    auth: "any_authenticated",
    scopes: ["read"],
    idempotency: "none",
    responseSchema: "ArtifactDetail",
    errors: commonReadErrors,
  },
  {
    id: "artifacts.publish",
    app: "api",
    method: "POST",
    path: "/v1/artifacts/{artifact_id}/publish",
    auth: "any_authenticated",
    scopes: ["write", "read", "share"],
    idempotency: "required",
    requestSchema: "PublishRequest",
    responseSchema: "PublishResult",
    errors: [
      ...commonMutationErrors,
      "draft_revision_conflict",
      "entrypoint_not_in_revision",
      "render_mode_incompatible",
      "access_link_lockdown_active",
      "usage_policy_exceeded",
    ],
  },
  {
    id: "artifacts.agentView",
    app: "api",
    method: "GET",
    path: "/v1/artifacts/{artifact_id}/agent-view",
    auth: "any_authenticated",
    scopes: ["read"],
    idempotency: "none",
    responseSchema: "AgentView",
    errors: commonReadErrors,
  },
  {
    id: "artifacts.updateDisplayMetadata",
    app: "api",
    method: "PATCH",
    path: "/v1/artifacts/{artifact_id}/display-metadata",
    auth: "any_authenticated",
    scopes: ["write"],
    idempotency: "required",
    requestSchema: "UpdateDisplayMetadataRequest",
    responseSchema: "UpdateDisplayMetadataResponse",
    errors: commonMutationErrors,
  },
  {
    id: "artifacts.delete",
    app: "api",
    method: "DELETE",
    path: "/v1/artifacts/{artifact_id}",
    auth: "any_authenticated",
    scopes: ["write"],
    idempotency: "required",
    requestSchema: "DeleteArtifactRequest",
    responseSchema: "DeleteArtifactResponse",
    errors: commonMutationErrors,
  },
  {
    id: "artifacts.listRevisions",
    app: "api",
    method: "GET",
    path: "/v1/artifacts/{artifact_id}/revisions",
    auth: "any_authenticated",
    scopes: ["read"],
    idempotency: "none",
    requestSchema: "PaginationRequest",
    responseSchema: "RevisionListResponse",
    errors: commonReadErrors,
  },
  {
    id: "artifacts.revisionAgentView",
    app: "api",
    method: "GET",
    path: "/v1/artifacts/{artifact_id}/revisions/{revision_id}/agent-view",
    auth: "any_authenticated",
    scopes: ["read"],
    idempotency: "none",
    responseSchema: "AgentView",
    errors: [...commonReadErrors, "revision_not_found", "revision_retained"],
  },
  {
    id: "artifacts.discardDraft",
    app: "api",
    method: "DELETE",
    path: "/v1/artifacts/{artifact_id}/drafts/{revision_id}",
    auth: "any_authenticated",
    scopes: ["write"],
    idempotency: "required",
    responseSchema: "DiscardDraftRevisionResponse",
    errors: [...commonMutationErrors, "revision_not_found"],
  },
  {
    id: "artifacts.enterAccessLinkLockdown",
    app: "api",
    method: "POST",
    path: "/v1/artifacts/{artifact_id}/access-link-lockdown",
    auth: "any_authenticated",
    scopes: ["share"],
    idempotency: "required",
    responseSchema: "AccessLinkLockdownResponse",
    errors: commonMutationErrors,
  },
  {
    id: "artifacts.liftAccessLinkLockdown",
    app: "api",
    method: "DELETE",
    path: "/v1/artifacts/{artifact_id}/access-link-lockdown",
    auth: "any_authenticated",
    scopes: ["share"],
    idempotency: "required",
    responseSchema: "AccessLinkLockdownResponse",
    errors: commonMutationErrors,
  },
  {
    id: "artifacts.getAccessLinkLockdown",
    app: "api",
    method: "GET",
    path: "/v1/artifacts/{artifact_id}/access-link-lockdown",
    auth: "any_authenticated",
    scopes: ["read", "share"],
    idempotency: "none",
    responseSchema: "AccessLinkLockdownResponse",
    errors: commonReadErrors,
  },
  {
    id: "artifacts.pin",
    app: "api",
    method: "POST",
    path: "/v1/artifacts/{artifact_id}/pin",
    auth: "member_dashboard",
    scopes: ["manage_workspace"],
    idempotency: "required",
    responseSchema: "PinArtifactResponse",
    errors: commonMutationErrors,
  },
  {
    id: "artifacts.unpin",
    app: "api",
    method: "DELETE",
    path: "/v1/artifacts/{artifact_id}/pin",
    auth: "member_dashboard",
    scopes: ["manage_workspace"],
    idempotency: "required",
    responseSchema: "PinArtifactResponse",
    errors: commonMutationErrors,
  },
  {
    id: "accessLinks.create",
    app: "api",
    method: "POST",
    path: "/v1/artifacts/{artifact_id}/access-links",
    auth: "any_authenticated",
    scopes: ["read", "share"],
    idempotency: "required",
    requestSchema: "CreateAccessLinkRequest",
    responseSchema: "CreateAccessLinkResponse",
    errors: [...commonMutationErrors, "access_link_lockdown_active", "usage_policy_exceeded"],
  },
  {
    id: "accessLinks.list",
    app: "api",
    method: "GET",
    path: "/v1/artifacts/{artifact_id}/access-links",
    auth: "any_authenticated",
    scopes: ["read", "share"],
    idempotency: "none",
    requestSchema: "PaginationRequest",
    responseSchema: "AccessLinkListResponse",
    errors: commonReadErrors,
  },
  {
    id: "accessLinks.mint",
    app: "api",
    method: "POST",
    path: "/v1/access-links/{access_link_id}/mint",
    auth: "any_authenticated",
    scopes: ["read", "share"],
    idempotency: "none",
    responseSchema: "MintAccessLinkResponse",
    errors: [...commonReadErrors, "access_link_lockdown_active", "not_found"],
  },
  {
    id: "accessLinks.revoke",
    app: "api",
    method: "DELETE",
    path: "/v1/access-links/{access_link_id}",
    auth: "any_authenticated",
    scopes: ["share"],
    idempotency: "required",
    responseSchema: "RevokeAccessLinkResponse",
    errors: commonMutationErrors,
  },
  {
    id: "accessLinks.resolve",
    app: "api",
    method: "POST",
    path: "/v1/access-links/resolve",
    auth: "none",
    scopes: [],
    idempotency: "none",
    requestSchema: "ResolveAccessLinkRequest",
    responseSchema: "ResolveAccessLinkResponse",
    errors: ["not_found", "rate_limited_artifact", "database_unavailable"],
  },
  {
    id: "apiKeys.list",
    app: "api",
    method: "GET",
    path: "/v1/api-keys",
    auth: "member_dashboard",
    scopes: ["manage_keys"],
    idempotency: "none",
    requestSchema: "PaginationRequest",
    responseSchema: "ApiKeyListResponse",
    errors: ["not_authenticated", "insufficient_scope", "database_unavailable"],
  },
  {
    id: "apiKeys.create",
    app: "api",
    method: "POST",
    path: "/v1/api-keys",
    auth: "member_dashboard",
    scopes: ["manage_keys"],
    idempotency: "required",
    requestSchema: "CreateApiKeyRequest",
    responseSchema: "CreateApiKeyResponse",
    errors: [
      "not_authenticated",
      "insufficient_scope",
      "invalid_idempotency_key",
      "idempotency_in_flight",
      "database_unavailable",
    ],
  },
  {
    id: "apiKeys.revoke",
    app: "api",
    method: "DELETE",
    path: "/v1/api-keys/{api_key_id}",
    auth: "member_dashboard",
    scopes: ["manage_keys"],
    idempotency: "required",
    responseSchema: "RevokeApiKeyResponse",
    errors: ["not_authenticated", "insufficient_scope", "api_key_not_found", "database_unavailable"],
  },
  {
    id: "auditEvents.list",
    app: "api",
    method: "GET",
    path: "/v1/audit-events",
    auth: "member_dashboard",
    scopes: ["read_audit"],
    idempotency: "none",
    requestSchema: "PaginationRequest",
    responseSchema: "AuditEventListResponse",
    errors: ["not_authenticated", "insufficient_scope", "database_unavailable"],
  },
  {
    id: "workspace.update",
    app: "api",
    method: "PATCH",
    path: "/v1/workspace",
    auth: "member_dashboard",
    scopes: ["manage_workspace"],
    idempotency: "required",
    requestSchema: "UpdateWorkspaceRequest",
    responseSchema: "UpdateWorkspaceResponse",
    errors: [
      "not_authenticated",
      "insufficient_scope",
      "invalid_idempotency_key",
      "idempotency_in_flight",
      "database_unavailable",
    ],
  },
  {
    id: "uploadSessions.create",
    app: "upload",
    method: "POST",
    path: "/v1/upload-sessions",
    auth: "any_authenticated",
    scopes: ["write"],
    idempotency: "required",
    requestSchema: "CreateUploadSessionRequest",
    responseSchema: "CreateUploadSessionResponse",
    errors: [
      "not_authenticated",
      "insufficient_scope",
      "file_count_cap_exceeded",
      "file_size_cap_exceeded",
      "revision_size_cap_exceeded",
      "database_unavailable",
    ],
  },
  {
    id: "uploadSessions.refreshFileUrl",
    app: "upload",
    method: "POST",
    path: "/v1/upload-sessions/{session_id}/files/refresh-url",
    auth: "any_authenticated",
    scopes: ["write"],
    idempotency: "none",
    requestSchema: "RefreshUploadUrlRequest",
    responseSchema: "RefreshUploadUrlResponse",
    errors: ["not_authenticated", "insufficient_scope", "upload_session_not_found", "upload_session_expired"],
  },
  {
    id: "uploadSessions.finalize",
    app: "upload",
    method: "POST",
    path: "/v1/upload-sessions/{session_id}/finalize",
    auth: "any_authenticated",
    scopes: ["write"],
    idempotency: "required",
    responseSchema: "FinalizeUploadSessionResponse",
    errors: [
      "not_authenticated",
      "insufficient_scope",
      "upload_session_not_found",
      "upload_session_expired",
      "unexpected_upload_object",
      "draft_revision_conflict",
      "database_unavailable",
    ],
  },
  {
    id: "uploadSessions.abandon",
    app: "upload",
    method: "DELETE",
    path: "/v1/upload-sessions/{session_id}",
    auth: "any_authenticated",
    scopes: ["write"],
    idempotency: "required",
    responseSchema: "AbandonUploadSessionResponse",
    errors: ["not_authenticated", "insufficient_scope", "upload_session_not_found", "database_unavailable"],
  },
  {
    id: "content.file",
    app: "content",
    method: "GET",
    path: "/v/{token}/{path}",
    auth: "none",
    scopes: [],
    idempotency: "none",
    responseSchema: "R2ObjectBody",
    errors: ["not_found", "rate_limited_artifact"],
  },
  {
    id: "content.bundle",
    app: "content",
    method: "GET",
    path: "/b/{token}",
    auth: "none",
    scopes: [],
    idempotency: "none",
    responseSchema: "R2ObjectBody",
    errors: ["not_found", "rate_limited_artifact"],
  },
  {
    id: "admin.platformLockdown",
    app: "admin",
    method: "POST",
    path: "/admin/platform-lockdowns",
    auth: "operator",
    scopes: [],
    idempotency: "required",
    requestSchema: "PlatformLockdownRequest",
    responseSchema: "PlatformLockdownResponse",
    errors: ["not_found", "invalid_idempotency_key", "idempotency_in_flight", "database_unavailable"],
  },
] as const satisfies readonly RouteContract[];
