import type { LegalDocument } from "./legal.js";

export const PRIVACY: LegalDocument = {
  path: "/privacy",
  title: "Privacy Policy",
  eyebrow: "Privacy and data protection",
  description: "How agent-paste collects, uses, stores, protects, and shares service data.",
  lead: "This policy explains what information Zaks.io, LLC processes when providing the agent-paste hosted service, why we process it, how we protect it, and the choices you have.",
  effectiveDate: "June 4, 2026",
  sections: [
    {
      id: "information-we-collect",
      title: "Information we collect",
      blocks: [
        {
          kind: "paragraph",
          text: "We collect information you provide, information generated by your use of the service, and limited technical information needed to operate, secure, and debug the service.",
        },
        {
          kind: "list",
          items: [
            "account and Workspace data, such as your email address, authentication provider identifiers, Workspace membership, settings, and Plan",
            "Artifact data, such as uploaded files, file paths, display metadata, Revision records, Bundle state, Access Link state, and claim or expiration state",
            "credential metadata, such as API Key name, public identifier, scopes, creation time, expiration, revocation state, and last-used timestamps, but not recoverable API Key secrets",
            "usage and security data, such as request metadata, IP address, user agent, route, status code, rate-limit state, audit events, abuse signals, and operational diagnostics",
            "billing data when paid features are enabled, generally handled by a payment provider rather than stored directly by agent-paste",
          ],
        },
      ],
    },
    {
      id: "how-we-use-information",
      title: "How we use information",
      blocks: [
        {
          kind: "paragraph",
          text: "We use service data to authenticate users, provision Workspaces, publish and serve Artifacts, resolve Access Links, enforce limits, maintain audit records, provide support, detect abuse, protect the service, improve reliability, and comply with legal obligations.",
        },
        {
          kind: "paragraph",
          text: "We do not sell personal information and do not run cross-context behavioral advertising on the service.",
        },
      ],
    },
    {
      id: "how-we-share-information",
      title: "How we share information",
      blocks: [
        {
          kind: "paragraph",
          text: "We share information only as needed to operate the service, comply with law, protect users and the platform, complete business transactions, or with your direction through features such as Access Links.",
        },
        {
          kind: "paragraph",
          text: "Service providers may process information for hosting, storage, authentication, security, payment processing, error monitoring, and operational tooling. They are authorized to use that information only to provide services to Zaks.io, LLC or as otherwise permitted by law.",
        },
      ],
    },
    {
      id: "data-storage-and-protection",
      title: "How we store and protect data",
      blocks: [
        {
          kind: "paragraph",
          text: "This is the public version of our storage and protection model. It describes the protections users should know about without publishing internal key names, exact topology, operational runbooks, or other details that would help an attacker.",
        },
        {
          kind: "list",
          items: [
            "Workspace data is isolated by tenant controls, application authorization, and database-level access rules.",
            "Artifact bytes are stored in private object storage and encrypted at the application layer before durable storage. The public content path does not expose direct object-store URLs.",
            "Untrusted Content is served from an isolated content origin with restrictive browser security headers and sandboxing appropriate to the content and trust tier.",
            "API Key secrets are shown only when created, stored in non-recoverable verifier form, and must be replaced if lost.",
            "Access Links use signed, revocable URLs. Sensitive link material is designed to avoid normal server-side logs where practical.",
            "Operational logs and audit summaries are designed to exclude request bodies, credential secrets, full signed URLs, and other high-risk values.",
            "Human access uses a dedicated authentication provider. Abuse-response controls are separated from normal API Key access.",
            "Security-sensitive secrets are handled through managed secret storage and rotation procedures, not committed to the repository.",
            "Automated and manual controls may rate-limit, revoke, disable, or delete content when needed for security, abuse response, or policy enforcement.",
          ],
        },
        {
          kind: "paragraph",
          text: "No internet service can guarantee absolute security. If you believe you found a vulnerability, do not test against other users' data. Report it privately through the Security Policy.",
        },
      ],
    },
    {
      id: "published-content-and-links",
      title: "Published content and links",
      blocks: [
        {
          kind: "paragraph",
          text: "When you publish an Artifact or share an Access Link, people or agents with the relevant link may be able to view the content until the link or Artifact expires, is revoked, is deleted, or is locked down. Treat shared links as sensitive.",
        },
        {
          kind: "paragraph",
          text: "Ephemeral publishing allows an agent to publish before a human claims the Workspace. Ephemeral content has shorter retention and lower limits. Claim links should be protected because they can transfer control of the published content.",
        },
      ],
    },
    {
      id: "retention-and-deletion",
      title: "Retention and deletion",
      blocks: [
        {
          kind: "paragraph",
          text: "Retention depends on the type of data and the Workspace settings or Plan. Artifacts may expire automatically. Audit, security, billing, abuse-prevention, and operational records may be kept longer where needed to operate the service, resolve disputes, enforce terms, or meet legal obligations.",
        },
        {
          kind: "paragraph",
          text: "Deletion can make content inaccessible before all backups, logs, caches, or queued cleanup jobs have aged out or completed.",
        },
      ],
    },
    {
      id: "cookies-and-session-data",
      title: "Cookies and session data",
      blocks: [
        {
          kind: "paragraph",
          text: "The apex marketing pages are designed not to set cookies. The dashboard uses session cookies and related authentication data to keep you signed in and protect the login flow. Browser or provider security controls may also set technical cookies needed for authentication or abuse prevention.",
        },
      ],
    },
    {
      id: "your-choices",
      title: "Your choices",
      blocks: [
        {
          kind: "paragraph",
          text: "You can manage API Keys, Access Links, Workspace settings, and Artifact lifecycle settings in the dashboard where those features are available. You can also delete content or revoke links when you no longer want them accessible.",
        },
        {
          kind: "paragraph",
          text: "Depending on where you live, you may have rights to access, correct, delete, or export certain personal information, or to object to some processing. Send requests to contact@agent-paste.sh.",
        },
      ],
    },
    {
      id: "age-requirement",
      title: "Age requirement",
      blocks: [
        {
          kind: "paragraph",
          text: "The service is only for people who are at least 18 years old. We do not knowingly collect personal information from anyone under 18.",
        },
      ],
    },
    {
      id: "availability-and-processing",
      title: "Availability and processing",
      blocks: [
        {
          kind: "paragraph",
          text: "The hosted service is currently offered only in the United States. Zaks.io, LLC and its providers may process information in the United States and, where provider operations require it, other jurisdictions with privacy laws different from where you live.",
        },
      ],
    },
    {
      id: "policy-changes",
      title: "Policy changes",
      blocks: [
        {
          kind: "paragraph",
          text: "We may update this policy as the service changes. The effective date above shows when this version took effect.",
        },
      ],
    },
    {
      id: "contact",
      title: "Contact",
      blocks: [
        {
          kind: "paragraph",
          text: "The hosted service is operated by Zaks.io, LLC. Privacy questions and data-rights requests can be sent to contact@agent-paste.sh.",
        },
        {
          kind: "paragraph",
          text: "Mailing address: Zaks.io, LLC, 2108 N St, Ste N, Sacramento, CA 95816, USA.",
        },
      ],
    },
  ],
};
