import { routeErrorGroups } from "./errors.js";

const { apiKeyMutation: apiKeyMutationErrors } = routeErrorGroups;

/**
 * Upload and content Worker route contracts, split out of `registry.ts` to keep
 * each file under the `noExcessiveLinesPerFile` limit. Spread into
 * `routeContracts` with `as const` so route-id literal inference is preserved.
 */
export const storageRouteContracts = [
  {
    id: "uploadSessions.create",
    app: "upload",
    method: "POST",
    path: "/v1/upload-sessions",
    auth: "api_key_or_mcp_oauth",
    scopes: ["publish"],
    idempotency: "required",
    rateLimit: "actor",
    requestSchema: "CreateUploadSessionRequest",
    responseSchema: "CreateUploadSessionResponse",
    errors: [
      ...apiKeyMutationErrors,
      "artifact_not_found",
      "draft_revision_conflict",
      "entrypoint_not_in_revision",
      "file_count_cap_exceeded",
      "file_size_cap_exceeded",
      "revision_size_cap_exceeded",
      "invalid_request",
    ],
  },
  {
    id: "uploadSessions.putFile",
    app: "upload",
    method: "PUT",
    path: "/v1/upload-sessions/{upload_session_id}/files/{path}",
    auth: "signed_upload_url",
    scopes: [],
    idempotency: "none",
    rateLimit: "none",
    responseSchema: "EmptyObject",
    errors: [
      "not_found",
      "not_authenticated",
      "invalid_content_length",
      "file_size_cap_exceeded",
      "upload_session_expired",
      "upload_session_not_found",
      "unexpected_upload_object",
    ],
  },
  {
    id: "uploadSessions.finalize",
    app: "upload",
    method: "POST",
    path: "/v1/upload-sessions/{upload_session_id}/finalize",
    auth: "api_key_or_mcp_oauth",
    scopes: ["publish"],
    idempotency: "required",
    rateLimit: "actor",
    responseSchema: "FinalizeUploadSessionResponse",
    errors: [
      ...apiKeyMutationErrors,
      "artifact_not_found",
      "draft_revision_conflict",
      "entrypoint_not_in_revision",
      "file_count_cap_exceeded",
      "file_size_cap_exceeded",
      "revision_size_cap_exceeded",
      "invalid_request",
      "unexpected_upload_object",
      "upload_incomplete",
      "upload_session_expired",
      "upload_session_not_found",
    ],
  },
  {
    id: "content.get",
    app: "content",
    method: "GET",
    path: "/v/{token}/{path}",
    auth: "signed_content_token",
    scopes: [],
    idempotency: "none",
    rateLimit: "artifact",
    responseSchema: "Response",
    errors: ["not_found", "rate_limited_artifact"],
  },
  {
    id: "content.head",
    app: "content",
    method: "HEAD",
    path: "/v/{token}/{path}",
    auth: "signed_content_token",
    scopes: [],
    idempotency: "none",
    rateLimit: "artifact",
    responseSchema: "Response",
    errors: ["not_found", "rate_limited_artifact"],
  },
  {
    id: "content.bundle",
    app: "content",
    method: "GET",
    path: "/b/{token}",
    auth: "signed_content_token",
    scopes: [],
    idempotency: "none",
    rateLimit: "artifact",
    responseSchema: "Response",
    errors: ["not_found", "rate_limited_artifact"],
  },
  {
    id: "content.bundleHead",
    app: "content",
    method: "HEAD",
    path: "/b/{token}",
    auth: "signed_content_token",
    scopes: [],
    idempotency: "none",
    rateLimit: "artifact",
    responseSchema: "Response",
    errors: ["not_found", "rate_limited_artifact"],
  },
] as const;
