import { routeErrorGroups } from "./errors.js";

const { apiKeyActorRead: apiKeyActorReadErrors, apiKeyMutation: apiKeyMutationErrors } = routeErrorGroups;

/**
 * Artifact, revision, access-link, and agent-view API route contracts, split out
 * of `registry.ts` to keep each file under the `noExcessiveLinesPerFile` limit.
 * Spread into `routeContracts` with `as const` so route-id literal inference is preserved.
 */
export const artifactRouteContracts = [
  {
    id: "artifacts.list",
    app: "api",
    method: "GET",
    path: "/v1/artifacts",
    auth: "mcp_oauth",
    scopes: ["read"],
    idempotency: "none",
    rateLimit: "actor",
    responseSchema: "ArtifactListResponse",
    errors: [...apiKeyActorReadErrors, "forbidden", "invalid_cursor", "invalid_request"],
  },
  {
    id: "artifacts.delete",
    app: "api",
    method: "DELETE",
    path: "/v1/artifacts/{artifact_id}",
    auth: "mcp_oauth",
    scopes: ["publish"],
    idempotency: "none",
    rateLimit: "actor",
    responseSchema: "DeleteArtifactResponse",
    errors: [...apiKeyMutationErrors, "forbidden", "artifact_not_found"],
  },
  {
    id: "artifacts.updateDisplayMetadata",
    app: "api",
    method: "PATCH",
    path: "/v1/artifacts/{artifact_id}/display-metadata",
    auth: "mcp_oauth",
    scopes: ["publish"],
    idempotency: "none",
    rateLimit: "actor",
    requestSchema: "UpdateDisplayMetadataRequest",
    responseSchema: "DisplayMetadata",
    errors: [...apiKeyMutationErrors, "forbidden", "invalid_request", "artifact_not_found"],
  },
  {
    id: "accessLinks.create",
    app: "api",
    method: "POST",
    path: "/v1/artifacts/{artifact_id}/access-links",
    auth: "api_key_or_mcp_oauth",
    scopes: ["publish"],
    idempotency: "required",
    rateLimit: "actor",
    requestSchema: "CreateAccessLinkRequest",
    responseSchema: "CreateAccessLinkResponse",
    errors: [...apiKeyMutationErrors, "forbidden", "not_found", "artifact_not_found", "invalid_request"],
  },
  {
    id: "accessLinks.mint",
    app: "api",
    method: "POST",
    path: "/v1/access-links/{access_link_id}/mint",
    auth: "api_key_or_mcp_oauth",
    scopes: ["publish"],
    idempotency: "none",
    rateLimit: "actor",
    responseSchema: "AccessLinkSignedUrl",
    errors: [...apiKeyActorReadErrors, "forbidden", "not_found"],
  },
  {
    id: "accessLinks.list",
    app: "api",
    method: "GET",
    path: "/v1/artifacts/{artifact_id}/access-links",
    auth: "api_key_or_mcp_oauth",
    scopes: ["publish"],
    idempotency: "none",
    rateLimit: "actor",
    responseSchema: "McpListAccessLinksOutput",
    errors: [...apiKeyActorReadErrors, "forbidden", "artifact_not_found"],
  },
  {
    id: "accessLinks.revoke",
    app: "api",
    method: "POST",
    path: "/v1/access-links/{access_link_id}/revoke",
    auth: "api_key_or_mcp_oauth",
    scopes: ["publish"],
    idempotency: "none",
    rateLimit: "actor",
    responseSchema: "McpRevokeAccessLinkOutput",
    errors: [...apiKeyMutationErrors, "forbidden", "not_found", "storage_unavailable"],
  },
  {
    id: "agentView.getLatest",
    app: "api",
    method: "GET",
    path: "/v1/artifacts/{artifact_id}/agent-view",
    auth: "api_key_or_mcp_oauth",
    scopes: ["read"],
    idempotency: "none",
    rateLimit: "actor",
    responseSchema: "AgentView",
    errors: [...apiKeyActorReadErrors, "forbidden", "not_found"],
  },
  {
    id: "agentView.getRevision",
    app: "api",
    method: "GET",
    path: "/v1/artifacts/{artifact_id}/revisions/{revision_id}/agent-view",
    auth: "api_key_or_mcp_oauth",
    scopes: ["read"],
    idempotency: "none",
    rateLimit: "actor",
    responseSchema: "AgentView",
    errors: [...apiKeyActorReadErrors, "forbidden", "not_found", "revision_retained"],
  },
  {
    id: "artifacts.fileContent",
    app: "api",
    method: "GET",
    // The file path travels as ?path= (not a path segment): FilePath may contain
    // '/', which route-path building encodes and Hono ':param' will not match.
    // ?revision_id= pins the read to a specific Revision so a CLI diff base and
    // its inherit base are the same Revision; absent => latest (ADR 0090).
    path: "/v1/artifacts/{artifact_id}/file-content",
    auth: "api_key_or_mcp_oauth",
    scopes: ["read"],
    idempotency: "none",
    rateLimit: "actor",
    responseSchema: "ArtifactFileContent",
    // `forbidden` is required by the registrar guard-error invariant for any
    // api_key_or_mcp_oauth read route (mirrors agentView.getLatest), even though
    // this handler resolves access via getAgentView and only ever returns
    // not_found / storage_unavailable.
    errors: [...apiKeyActorReadErrors, "forbidden", "not_found", "storage_unavailable"],
  },
  {
    id: "revisions.list",
    app: "api",
    method: "GET",
    path: "/v1/artifacts/{artifact_id}/revisions",
    auth: "api_key_or_mcp_oauth",
    scopes: ["read"],
    idempotency: "none",
    rateLimit: "actor",
    responseSchema: "RevisionListResponse",
    errors: [...apiKeyActorReadErrors, "forbidden", "artifact_not_found"],
  },
  {
    id: "revisions.publish",
    app: "api",
    method: "POST",
    path: "/v1/artifacts/{artifact_id}/revisions/{revision_id}/publish",
    auth: "api_key_or_mcp_oauth",
    scopes: ["publish"],
    idempotency: "required",
    rateLimit: "actor",
    allowEmptyBody: true,
    requestSchema: "PublishRevisionRequest",
    responseSchema: "PublishResult",
    errors: [
      ...apiKeyMutationErrors,
      "artifact_not_found",
      "draft_revision_conflict",
      "entrypoint_not_in_revision",
      "invalid_request",
      "revision_retained",
      "revision_unpublished",
      "write_allowance_exceeded",
      "storage_unavailable",
    ],
  },
] as const;
