import { routeErrorGroups } from "./errors.js";
import type { RouteContract } from "./types.js";

const {
  apiKeyRead: apiKeyReadErrors,
  apiKeyActorRead: apiKeyActorReadErrors,
  apiKeyMutation: apiKeyMutationErrors,
  webRead: webReadErrors,
  webActorRead: webActorReadErrors,
  webIdempotentMutation: webIdempotentMutationErrors,
  webCallback: webCallbackErrors,
  operatorMutation: operatorMutationErrors,
  operatorRead: operatorReadErrors,
  ephemeralProvision: ephemeralProvisionErrors,
  ephemeralClaim: ephemeralClaimErrors,
} = routeErrorGroups;

export const routeContracts = [
  {
    id: "whoami.get",
    app: "api",
    method: "GET",
    path: "/v1/whoami",
    auth: "api_key",
    scopes: [],
    idempotency: "none",
    rateLimit: "actor",
    responseSchema: "WhoamiResponse",
    errors: apiKeyActorReadErrors,
  },
  {
    id: "mcp.whoami",
    app: "api",
    method: "GET",
    path: "/v1/mcp/whoami",
    auth: "mcp_oauth",
    scopes: [],
    idempotency: "none",
    rateLimit: "actor",
    responseSchema: "McpWhoamiResponse",
    errors: [
      "not_authenticated",
      "forbidden",
      "database_unavailable",
      "rate_limited_actor",
      "rate_limited_workspace",
    ] as const,
  },
  {
    id: "usagePolicy.get",
    app: "api",
    method: "GET",
    path: "/v1/usage-policy",
    auth: "api_key",
    scopes: [],
    idempotency: "none",
    rateLimit: "none",
    responseSchema: "UsagePolicy",
    errors: apiKeyReadErrors,
  },
  {
    id: "apiKeys.revokeCurrent",
    app: "api",
    method: "POST",
    path: "/v1/api-keys/current/revoke",
    auth: "api_key",
    scopes: [],
    idempotency: "none",
    rateLimit: "actor",
    responseSchema: "RevokeApiKeyResponse",
    errors: apiKeyActorReadErrors,
  },
  {
    id: "agentView.public",
    app: "api",
    method: "GET",
    path: "/v1/public/agent-view/{token}",
    auth: "signed_agent_view_token",
    scopes: [],
    idempotency: "none",
    rateLimit: "artifact",
    responseSchema: "AgentView",
    errors: ["not_found", "database_unavailable", "rate_limited_artifact"],
  },
  {
    id: "accessLinks.resolve",
    app: "api",
    method: "POST",
    path: "/v1/access-links/resolve",
    auth: "none",
    scopes: [],
    idempotency: "none",
    rateLimit: "none",
    requestSchema: "AccessLinkResolveRequest",
    responseSchema: "AccessLinkResolveResponse",
    errors: ["not_found", "invalid_request", "database_unavailable", "rate_limited_artifact"],
  },
  {
    id: "ephemeral.provision",
    app: "api",
    method: "POST",
    path: "/v1/ephemeral/provision",
    auth: "none",
    scopes: [],
    idempotency: "none",
    rateLimit: "ephemeral_provision",
    allowEmptyBody: true,
    requestSchema: "EphemeralProvisionRequest",
    responseSchema: "EphemeralProvisionResponse",
    errors: ephemeralProvisionErrors,
  },
  {
    id: "ephemeral.claim",
    app: "api",
    method: "POST",
    path: "/v1/ephemeral/claim",
    auth: "workos_access_token",
    scopes: [],
    idempotency: "required",
    rateLimit: "actor",
    requestSchema: "EphemeralClaimRequest",
    responseSchema: "EphemeralClaimResponse",
    errors: ephemeralClaimErrors,
  },
  {
    id: "artifacts.list",
    app: "api",
    method: "GET",
    path: "/v1/artifacts",
    auth: "mcp_oauth",
    scopes: ["read"],
    idempotency: "none",
    rateLimit: "actor",
    responseSchema: "ArtifactListResponse",
    errors: [...apiKeyActorReadErrors, "forbidden", "invalid_cursor", "invalid_request"],
  },
  {
    id: "artifacts.delete",
    app: "api",
    method: "DELETE",
    path: "/v1/artifacts/{artifact_id}",
    auth: "mcp_oauth",
    scopes: ["publish"],
    idempotency: "none",
    rateLimit: "actor",
    responseSchema: "DeleteArtifactResponse",
    errors: [...apiKeyMutationErrors, "forbidden", "artifact_not_found"],
  },
  {
    id: "artifacts.updateDisplayMetadata",
    app: "api",
    method: "PATCH",
    path: "/v1/artifacts/{artifact_id}/display-metadata",
    auth: "mcp_oauth",
    scopes: ["publish"],
    idempotency: "none",
    rateLimit: "actor",
    requestSchema: "UpdateDisplayMetadataRequest",
    responseSchema: "DisplayMetadata",
    errors: [...apiKeyMutationErrors, "forbidden", "invalid_request", "artifact_not_found"],
  },
  {
    id: "accessLinks.create",
    app: "api",
    method: "POST",
    path: "/v1/artifacts/{artifact_id}/access-links",
    auth: "mcp_oauth",
    scopes: ["admin"],
    idempotency: "required",
    rateLimit: "actor",
    requestSchema: "CreateAccessLinkRequest",
    responseSchema: "CreateAccessLinkResponse",
    errors: [...apiKeyMutationErrors, "forbidden", "not_found", "artifact_not_found", "invalid_request"],
  },
  {
    id: "accessLinks.mint",
    app: "api",
    method: "POST",
    path: "/v1/access-links/{access_link_id}/mint",
    auth: "mcp_oauth",
    scopes: ["admin"],
    idempotency: "none",
    rateLimit: "actor",
    responseSchema: "AccessLinkSignedUrl",
    errors: [...apiKeyActorReadErrors, "forbidden", "not_found"],
  },
  {
    id: "accessLinks.list",
    app: "api",
    method: "GET",
    path: "/v1/artifacts/{artifact_id}/access-links",
    auth: "mcp_oauth",
    scopes: ["admin"],
    idempotency: "none",
    rateLimit: "actor",
    responseSchema: "McpListAccessLinksOutput",
    errors: [...apiKeyActorReadErrors, "forbidden", "artifact_not_found"],
  },
  {
    id: "accessLinks.revoke",
    app: "api",
    method: "POST",
    path: "/v1/access-links/{access_link_id}/revoke",
    auth: "mcp_oauth",
    scopes: ["admin"],
    idempotency: "none",
    rateLimit: "actor",
    responseSchema: "McpRevokeAccessLinkOutput",
    errors: [...apiKeyMutationErrors, "forbidden", "not_found"],
  },
  {
    id: "agentView.getLatest",
    app: "api",
    method: "GET",
    path: "/v1/artifacts/{artifact_id}/agent-view",
    auth: "api_key_or_mcp_oauth",
    scopes: ["read"],
    idempotency: "none",
    rateLimit: "actor",
    responseSchema: "AgentView",
    errors: [...apiKeyActorReadErrors, "forbidden", "not_found"],
  },
  {
    id: "agentView.getRevision",
    app: "api",
    method: "GET",
    path: "/v1/artifacts/{artifact_id}/revisions/{revision_id}/agent-view",
    auth: "api_key_or_mcp_oauth",
    scopes: ["read"],
    idempotency: "none",
    rateLimit: "actor",
    responseSchema: "AgentView",
    errors: [...apiKeyActorReadErrors, "forbidden", "not_found", "revision_retained"],
  },
  {
    id: "revisions.list",
    app: "api",
    method: "GET",
    path: "/v1/artifacts/{artifact_id}/revisions",
    auth: "api_key_or_mcp_oauth",
    scopes: ["read"],
    idempotency: "none",
    rateLimit: "actor",
    responseSchema: "RevisionListResponse",
    errors: [...apiKeyActorReadErrors, "forbidden", "artifact_not_found"],
  },
  {
    id: "revisions.publish",
    app: "api",
    method: "POST",
    path: "/v1/artifacts/{artifact_id}/revisions/{revision_id}/publish",
    auth: "api_key_or_mcp_oauth",
    scopes: ["publish"],
    idempotency: "required",
    rateLimit: "actor",
    responseSchema: "PublishResult",
    errors: [
      ...apiKeyMutationErrors,
      "artifact_not_found",
      "draft_revision_conflict",
      "entrypoint_not_in_revision",
      "revision_retained",
      "revision_unpublished",
    ],
  },
  {
    id: "web.auth.callback",
    app: "api",
    method: "POST",
    path: "/v1/auth/web/callback",
    auth: "workos_access_token",
    scopes: [],
    idempotency: "none",
    rateLimit: "none",
    allowUnprovisioned: true,
    responseSchema: "WebAuthCallbackResponse",
    errors: webCallbackErrors,
  },
  {
    id: "web.workspace.get",
    app: "api",
    method: "GET",
    path: "/v1/web/workspace",
    auth: "workos_access_token",
    scopes: [],
    idempotency: "none",
    rateLimit: "actor",
    responseSchema: "WebWorkspaceResponse",
    errors: webActorReadErrors,
  },
  {
    id: "web.artifacts.list",
    app: "api",
    method: "GET",
    path: "/v1/web/artifacts",
    auth: "workos_access_token",
    scopes: ["read"],
    idempotency: "none",
    rateLimit: "actor",
    responseSchema: "WebArtifactListResponse",
    errors: [...webActorReadErrors, "invalid_cursor", "invalid_request"],
  },
  {
    id: "web.artifacts.get",
    app: "api",
    method: "GET",
    path: "/v1/web/artifacts/{artifact_id}",
    auth: "workos_access_token",
    scopes: ["read"],
    idempotency: "none",
    rateLimit: "actor",
    responseSchema: "WebArtifactDetailResponse",
    errors: [...webActorReadErrors, "not_found"],
  },
  {
    id: "web.artifacts.pin",
    app: "api",
    method: "POST",
    path: "/v1/web/artifacts/{artifact_id}/pin",
    auth: "workos_access_token",
    scopes: ["read"],
    idempotency: "required",
    rateLimit: "actor",
    responseSchema: "WebArtifactDetailResponse",
    errors: [...webIdempotentMutationErrors, "not_found", "artifact_not_found", "pinned_artifact_cap_exceeded"],
  },
  {
    id: "web.artifacts.unpin",
    app: "api",
    method: "POST",
    path: "/v1/web/artifacts/{artifact_id}/unpin",
    auth: "workos_access_token",
    scopes: ["read"],
    idempotency: "required",
    rateLimit: "actor",
    responseSchema: "WebArtifactDetailResponse",
    errors: [...webIdempotentMutationErrors, "not_found", "artifact_not_found"],
  },
  {
    id: "web.apiKeys.list",
    app: "api",
    method: "GET",
    path: "/v1/web/keys",
    auth: "workos_access_token",
    scopes: ["admin"],
    idempotency: "none",
    rateLimit: "actor",
    responseSchema: "WebApiKeyListResponse",
    errors: webActorReadErrors,
  },
  {
    id: "web.apiKeys.create",
    app: "api",
    method: "POST",
    path: "/v1/web/keys",
    auth: "workos_access_token",
    scopes: ["admin"],
    idempotency: "required",
    rateLimit: "actor",
    requestSchema: "CreateApiKeyRequest",
    responseSchema: "CreateApiKeyResponse",
    errors: webIdempotentMutationErrors,
  },
  {
    id: "web.apiKeys.revoke",
    app: "api",
    method: "POST",
    path: "/v1/web/keys/{api_key_id}/revoke",
    auth: "workos_access_token",
    scopes: ["admin"],
    idempotency: "required",
    rateLimit: "actor",
    responseSchema: "RevokeApiKeyResponse",
    errors: [...webIdempotentMutationErrors, "not_found"],
  },
  {
    id: "web.audit.list",
    app: "api",
    method: "GET",
    path: "/v1/web/audit",
    auth: "workos_access_token",
    scopes: ["admin"],
    idempotency: "none",
    rateLimit: "actor",
    responseSchema: "WebAuditListResponse",
    errors: [...webActorReadErrors, "invalid_cursor", "invalid_request"],
  },
  {
    id: "web.settings.get",
    app: "api",
    method: "GET",
    path: "/v1/web/settings",
    auth: "workos_access_token",
    scopes: ["admin"],
    idempotency: "none",
    rateLimit: "actor",
    responseSchema: "WebSettingsResponse",
    errors: webActorReadErrors,
  },
  {
    id: "web.settings.update",
    app: "api",
    method: "PATCH",
    path: "/v1/web/settings",
    auth: "workos_access_token",
    scopes: ["admin"],
    idempotency: "required",
    rateLimit: "actor",
    requestSchema: "UpdateWebSettingsRequest",
    responseSchema: "WebSettingsResponse",
    errors: webIdempotentMutationErrors,
  },
  {
    id: "web.admin.lockdown.set",
    app: "api",
    method: "POST",
    path: "/v1/web/admin/lockdowns",
    auth: "operator",
    scopes: [],
    idempotency: "required",
    rateLimit: "actor",
    requestSchema: "SetLockdownRequest",
    responseSchema: "LockdownDetail",
    errors: operatorMutationErrors,
  },
  {
    id: "web.admin.lockdown.list",
    app: "api",
    method: "GET",
    path: "/v1/web/admin/lockdowns",
    auth: "operator",
    scopes: [],
    idempotency: "none",
    rateLimit: "actor",
    responseSchema: "LockdownListResponse",
    errors: operatorReadErrors,
  },
  {
    id: "web.admin.lockdown.lift",
    app: "api",
    method: "DELETE",
    path: "/v1/web/admin/lockdowns/{scope}/{target_id}",
    auth: "operator",
    scopes: [],
    idempotency: "required",
    rateLimit: "actor",
    responseSchema: "LockdownDetail",
    errors: operatorMutationErrors,
  },
  {
    id: "web.admin.events.list",
    app: "api",
    method: "GET",
    path: "/v1/web/admin/events",
    auth: "operator",
    scopes: [],
    idempotency: "none",
    rateLimit: "actor",
    responseSchema: "WebOperatorEventListResponse",
    errors: operatorReadErrors,
  },
  {
    id: "uploadSessions.create",
    app: "upload",
    method: "POST",
    path: "/v1/upload-sessions",
    auth: "api_key_or_mcp_oauth",
    scopes: ["publish"],
    idempotency: "required",
    rateLimit: "actor",
    requestSchema: "CreateUploadSessionRequest",
    responseSchema: "CreateUploadSessionResponse",
    errors: [
      ...apiKeyMutationErrors,
      "artifact_not_found",
      "draft_revision_conflict",
      "file_count_cap_exceeded",
      "file_size_cap_exceeded",
      "revision_size_cap_exceeded",
      "invalid_request",
    ],
  },
  {
    id: "uploadSessions.putFile",
    app: "upload",
    method: "PUT",
    path: "/v1/upload-sessions/{upload_session_id}/files/{path}",
    auth: "signed_upload_url",
    scopes: [],
    idempotency: "none",
    rateLimit: "none",
    responseSchema: "EmptyObject",
    errors: [
      "not_found",
      "not_authenticated",
      "invalid_content_length",
      "file_size_cap_exceeded",
      "upload_session_expired",
      "upload_session_not_found",
      "unexpected_upload_object",
    ],
  },
  {
    id: "uploadSessions.finalize",
    app: "upload",
    method: "POST",
    path: "/v1/upload-sessions/{upload_session_id}/finalize",
    auth: "api_key_or_mcp_oauth",
    scopes: ["publish"],
    idempotency: "required",
    rateLimit: "actor",
    responseSchema: "FinalizeUploadSessionResponse",
    errors: [
      ...apiKeyMutationErrors,
      "artifact_not_found",
      "draft_revision_conflict",
      "entrypoint_not_in_revision",
      "unexpected_upload_object",
      "upload_incomplete",
      "upload_session_expired",
      "upload_session_not_found",
    ],
  },
  {
    id: "content.get",
    app: "content",
    method: "GET",
    path: "/v/{token}/{path}",
    auth: "signed_content_token",
    scopes: [],
    idempotency: "none",
    rateLimit: "artifact",
    responseSchema: "Response",
    errors: ["not_found", "rate_limited_artifact"],
  },
  {
    id: "content.head",
    app: "content",
    method: "HEAD",
    path: "/v/{token}/{path}",
    auth: "signed_content_token",
    scopes: [],
    idempotency: "none",
    rateLimit: "artifact",
    responseSchema: "Response",
    errors: ["not_found", "rate_limited_artifact"],
  },
  {
    id: "content.bundle",
    app: "content",
    method: "GET",
    path: "/b/{token}",
    auth: "signed_content_token",
    scopes: [],
    idempotency: "none",
    rateLimit: "artifact",
    responseSchema: "Response",
    errors: ["not_found", "rate_limited_artifact"],
  },
  {
    id: "content.bundleHead",
    app: "content",
    method: "HEAD",
    path: "/b/{token}",
    auth: "signed_content_token",
    scopes: [],
    idempotency: "none",
    rateLimit: "artifact",
    responseSchema: "Response",
    errors: ["not_found", "rate_limited_artifact"],
  },
] as const satisfies readonly RouteContract[];

export type RouteId = (typeof routeContracts)[number]["id"];
export type RouteContractById<Id extends RouteId> = Extract<(typeof routeContracts)[number], { id: Id }>;

export function routeContractById<Id extends RouteId>(id: Id): RouteContractById<Id> {
  const contract = routeContracts.find((route) => route.id === id);
  if (!contract) {
    throw new Error(`Unknown route contract: ${id}`);
  }
  return contract as RouteContractById<Id>;
}
