import { routeErrorGroups } from "./errors.js";

const {
  webActorRead: webActorReadErrors,
  webIdempotentMutation: webIdempotentMutationErrors,
  webCallback: webCallbackErrors,
} = routeErrorGroups;

/**
 * Web dashboard route contracts (non-operator), split out of `registry.ts` to keep
 * each file under the `noExcessiveLinesPerFile` limit. Spread into `routeContracts`
 * with `as const` so route-id literal inference is preserved.
 */
export const webRouteContracts = [
  {
    id: "web.auth.callback",
    app: "api",
    method: "POST",
    path: "/v1/auth/web/callback",
    auth: "workos_access_token",
    scopes: [],
    idempotency: "none",
    rateLimit: "none",
    allowUnprovisioned: true,
    responseSchema: "WebAuthCallbackResponse",
    errors: webCallbackErrors,
  },
  {
    id: "web.workspace.get",
    app: "api",
    method: "GET",
    path: "/v1/web/workspace",
    auth: "workos_access_token",
    scopes: [],
    idempotency: "none",
    rateLimit: "actor",
    responseSchema: "WebWorkspaceResponse",
    errors: webActorReadErrors,
  },
  {
    id: "web.artifacts.list",
    app: "api",
    method: "GET",
    path: "/v1/web/artifacts",
    auth: "workos_access_token",
    scopes: ["read"],
    idempotency: "none",
    rateLimit: "actor",
    responseSchema: "WebArtifactListResponse",
    errors: [...webActorReadErrors, "invalid_cursor", "invalid_request"],
  },
  {
    id: "web.artifacts.get",
    app: "api",
    method: "GET",
    path: "/v1/web/artifacts/{artifact_id}",
    auth: "workos_access_token",
    scopes: ["read"],
    idempotency: "none",
    rateLimit: "actor",
    responseSchema: "WebArtifactDetailResponse",
    errors: [...webActorReadErrors, "not_found"],
  },
  {
    id: "web.artifacts.pin",
    app: "api",
    method: "POST",
    path: "/v1/web/artifacts/{artifact_id}/pin",
    auth: "workos_access_token",
    scopes: ["read"],
    idempotency: "required",
    rateLimit: "actor",
    responseSchema: "WebArtifactDetailResponse",
    errors: [...webIdempotentMutationErrors, "not_found", "artifact_not_found", "pinned_artifact_cap_exceeded"],
  },
  {
    id: "web.artifacts.unpin",
    app: "api",
    method: "POST",
    path: "/v1/web/artifacts/{artifact_id}/unpin",
    auth: "workos_access_token",
    scopes: ["read"],
    idempotency: "required",
    rateLimit: "actor",
    responseSchema: "WebArtifactDetailResponse",
    errors: [...webIdempotentMutationErrors, "not_found", "artifact_not_found"],
  },
  {
    id: "web.apiKeys.list",
    app: "api",
    method: "GET",
    path: "/v1/web/keys",
    auth: "workos_access_token",
    scopes: ["admin"],
    idempotency: "none",
    rateLimit: "actor",
    responseSchema: "WebApiKeyListResponse",
    errors: webActorReadErrors,
  },
  {
    id: "web.apiKeys.create",
    app: "api",
    method: "POST",
    path: "/v1/web/keys",
    auth: "workos_access_token",
    scopes: ["admin"],
    idempotency: "required",
    rateLimit: "actor",
    requestSchema: "CreateApiKeyRequest",
    responseSchema: "CreateApiKeyResponse",
    errors: webIdempotentMutationErrors,
  },
  {
    id: "web.apiKeys.revoke",
    app: "api",
    method: "POST",
    path: "/v1/web/keys/{api_key_id}/revoke",
    auth: "workos_access_token",
    scopes: ["admin"],
    idempotency: "required",
    rateLimit: "actor",
    responseSchema: "RevokeApiKeyResponse",
    errors: [...webIdempotentMutationErrors, "not_found"],
  },
  {
    id: "web.accessLinks.listAll",
    app: "api",
    method: "GET",
    path: "/v1/web/access-links",
    auth: "workos_access_token",
    scopes: ["read"],
    idempotency: "none",
    rateLimit: "actor",
    responseSchema: "WebAccessLinkListResponse",
    errors: webActorReadErrors,
  },
  {
    id: "web.accessLinks.listForArtifact",
    app: "api",
    method: "GET",
    path: "/v1/web/artifacts/{artifact_id}/access-links",
    auth: "workos_access_token",
    scopes: ["read"],
    idempotency: "none",
    rateLimit: "actor",
    responseSchema: "WebAccessLinkListResponse",
    errors: [...webActorReadErrors, "artifact_not_found"],
  },
  {
    id: "web.revisions.list",
    app: "api",
    method: "GET",
    path: "/v1/web/artifacts/{artifact_id}/revisions",
    auth: "workos_access_token",
    scopes: ["read"],
    idempotency: "none",
    rateLimit: "actor",
    responseSchema: "RevisionListResponse",
    errors: [...webActorReadErrors, "artifact_not_found"],
  },
  {
    id: "web.accessLinks.create",
    app: "api",
    method: "POST",
    path: "/v1/web/artifacts/{artifact_id}/access-links",
    auth: "workos_access_token",
    scopes: ["read"],
    idempotency: "required",
    rateLimit: "actor",
    requestSchema: "CreateAccessLinkRequest",
    responseSchema: "CreateAccessLinkResponse",
    errors: [...webIdempotentMutationErrors, "not_found", "artifact_not_found"],
  },
  {
    id: "web.accessLinks.mint",
    app: "api",
    method: "POST",
    path: "/v1/web/access-links/{access_link_id}/mint",
    auth: "workos_access_token",
    scopes: ["read"],
    idempotency: "none",
    rateLimit: "actor",
    responseSchema: "AccessLinkSignedUrl",
    errors: [...webActorReadErrors, "not_found"],
  },
  {
    id: "web.accessLinks.revoke",
    app: "api",
    method: "POST",
    path: "/v1/web/access-links/{access_link_id}/revoke",
    auth: "workos_access_token",
    scopes: ["read"],
    idempotency: "none",
    rateLimit: "actor",
    responseSchema: "WebRevokeAccessLinkResponse",
    // revoke self-dedupes via uow.command (server-derived key), so a concurrent
    // collision can still surface idempotency_in_flight even though the client
    // does not supply an Idempotency-Key header. mint is a pure read and cannot.
    errors: [...webActorReadErrors, "not_found", "idempotency_in_flight"],
  },
  {
    id: "web.accessLinks.lockdown.set",
    app: "api",
    method: "POST",
    path: "/v1/web/artifacts/{artifact_id}/access-link-lockdown",
    auth: "workos_access_token",
    scopes: ["read"],
    idempotency: "required",
    rateLimit: "actor",
    responseSchema: "WebArtifactDetailResponse",
    errors: [...webIdempotentMutationErrors, "not_found", "artifact_not_found"],
  },
  {
    id: "web.accessLinks.lockdown.lift",
    app: "api",
    method: "POST",
    path: "/v1/web/artifacts/{artifact_id}/access-link-lockdown/lift",
    auth: "workos_access_token",
    scopes: ["read"],
    idempotency: "required",
    rateLimit: "actor",
    responseSchema: "WebArtifactDetailResponse",
    errors: [...webIdempotentMutationErrors, "not_found", "artifact_not_found"],
  },
  {
    id: "web.audit.list",
    app: "api",
    method: "GET",
    path: "/v1/web/audit",
    auth: "workos_access_token",
    scopes: ["admin"],
    idempotency: "none",
    rateLimit: "actor",
    responseSchema: "WebAuditListResponse",
    errors: [...webActorReadErrors, "invalid_cursor", "invalid_request"],
  },
  {
    id: "web.settings.get",
    app: "api",
    method: "GET",
    path: "/v1/web/settings",
    auth: "workos_access_token",
    scopes: ["admin"],
    idempotency: "none",
    rateLimit: "actor",
    responseSchema: "WebSettingsResponse",
    errors: webActorReadErrors,
  },
  {
    id: "web.settings.update",
    app: "api",
    method: "PATCH",
    path: "/v1/web/settings",
    auth: "workos_access_token",
    scopes: ["admin"],
    idempotency: "required",
    rateLimit: "actor",
    requestSchema: "UpdateWebSettingsRequest",
    responseSchema: "WebSettingsResponse",
    errors: webIdempotentMutationErrors,
  },
] as const;
